# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import spacextickets.core.validation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20180606_1515'),
        ('core', '0004_auto_20180619_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='order date')),
                ('booking_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='booking code')),
                ('is_temporary', models.BooleanField(default=True, verbose_name='temporary_order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BaseUser', validators=[spacextickets.core.validation.validate_order_user], verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'verbose_name': 'order',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='departing date')),
                ('ticket_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ticket code')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='order')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Traveler', verbose_name='traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScheduledTrip', verbose_name='trip')),
            ],
            options={
                'verbose_name_plural': 'tickets',
                'verbose_name': 'ticket',
            },
        ),
    ]
