# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import spacextickets.core.validation


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BaseUser', validators=[spacextickets.core.validation.validate_order_user], verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='traveler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Traveler', verbose_name='traveler'),
        ),
    ]
