# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180619_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='order date'),
        ),
    ]
