# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import spacextickets.core.validation


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180712_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(validators=[spacextickets.core.validation.validate_ticket_date], verbose_name='departing date'),
        ),
    ]
