# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20180624_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMap',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.City', verbose_name='city')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('long', models.FloatField(verbose_name='longitude')),
            ],
        ),
    ]
