# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180604_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='gender',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
