# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180604_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='email',
            field=models.CharField(default='test', max_length=30, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BaseUser', verbose_name='user'),
        ),
    ]
