# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180605_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'base user', 'verbose_name_plural': 'base users'},
        ),
        migrations.AlterModelOptions(
            name='guestuser',
            options={'verbose_name': 'guest user', 'verbose_name_plural': 'guest users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is superuser'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='birthday',
            field=models.DateField(verbose_name='birthday date'),
        ),
    ]
