# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180605_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestuser',
            options={},
        ),
    ]
