# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 15:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spacextickets.core.validation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('name_en', models.CharField(max_length=15, null=True, verbose_name='name')),
                ('name_it', models.CharField(max_length=15, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='order date')),
                ('booking_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='booking code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[spacextickets.core.validation.validate_order_user], verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of the week')),
                ('time', models.TimeField(help_text='in UTC time', verbose_name='departure time')),
                ('duration', models.DurationField(validators=[spacextickets.core.validation.validate_schedtrip_duration], verbose_name='duration')),
                ('seats', models.PositiveSmallIntegerField(default=3, help_text='maximum number', validators=[spacextickets.core.validation.validate_schedtrip_seats], verbose_name='seats')),
                ('price', models.DecimalField(decimal_places=2, help_text='in EUR', max_digits=9, validators=[spacextickets.core.validation.validate_schedtrip_price], verbose_name='price')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='core.City', verbose_name='arrival')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='core.City', verbose_name='departure')),
            ],
            options={
                'verbose_name': 'scheduled trip',
                'verbose_name_plural': 'scheduled trips',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=15, null=True, unique=True, verbose_name='name')),
                ('name_it', models.CharField(max_length=15, null=True, unique=True, verbose_name='name')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania')], max_length=2, verbose_name='continent')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='departing date')),
                ('ticket_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ticket code')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Order', verbose_name='order')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Traveler', verbose_name='traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScheduledTrip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State', verbose_name='state'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtrip',
            unique_together=set([('departure', 'arrival', 'week_day', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'state')]),
        ),
    ]
