# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180615_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
