# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180619_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrip',
            name='xime',
            field=models.TimeField(default=None, help_text='in UTC time', verbose_name='departure time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledtrip',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
