# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180624_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtrip',
            name='xime',
        ),
        migrations.AlterField(
            model_name='scheduledtrip',
            name='time',
            field=models.TimeField(help_text='in UTC time', verbose_name='departure time'),
        ),
    ]
